baseURL = 'https://blue-ground-095741c0f.6.azurestaticapps.net/'
languageCode = 'en-us'
title = 'Sridhar quick notes'
theme = "papermod"
[sitemap]
  changeFreq = 'Daily'
  filename = 'sitemap.xml'
  disabled = false
  priority = 0.8

